python train_idrid_supervised_2d_smp.py \
        --num_works 4 \
        --device 0 \
        --exp crop_IDRID_smp_UNet_ex/resnet50_shuffle/imgz800_bs4_Adam_CLAHE2_warmup0_newschduler_max_iterations-2500_polyv2_lr2e-3 \
        --dataset_name crop_IDRID \
        --image_size 800 \
        --model UNet \
        --optim Adam \
        --batch_size 4 \
        --warmup 0.0 \
        --base_lr 0.002 \
        --CLAHE 2 \
        --ce_weight 1 1 1 1 1 \
        --max_iterations 2500 \
        --backbone resnet50